kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: restricted-rolebinding
  namespace: default
subjects:
- kind: User
  name: jenkins-test-sa@sada-ala-radaoui.iam.gserviceaccount.com
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
