# Default values for iap-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ambassadorInstances:
  - ambassadorID: ambassador-1
    replicaCount: 8
    resources:
      limits:
        cpu: 1
        memory: 400Mi
      requests:
        cpu: 200m
        memory: 100Mi
    image:
      repository: quay.io/datawire/ambassador
      tag: 0.39.0
      pullPolicy: Always

ingresses:
  - name: test
    externalIpName: kubectl apply -f-
    certs:
      - mycert
    enable_container_native_lb: true
    routing:
      - name: face
        ambassadorID: ambassador-1
        optional_configurations:
          timeout_ms: 3800000
          connect_timeout_ms: 10000
          retry_policy:
            num_retries: 10
            retry_on: 5xx
        mapping:
          - name: host
            source: test.haktech.io
            destination: facebook.com
      - name: goog
        ambassadorID: ambassador-1
        mapping:
          - name: host
            source: ttest.haktech.io
            destination: google.com

nameOverride: ""
fullnameOverride: ""
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ambassador
